
import java.awt.*;
import javax.swing.*;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author I Komang Abimanyu/1402022066
 */
public class Library_1402022066 extends javax.swing.JFrame {
    //paketan cekLogin
    public boolean cekLogin(String username, String password, String roles){
        String sqlcon = "select * from data";
                
        try{
            ResultSet cek = dbConnect.con.createStatement().executeQuery(sqlcon);
            while(cek.next()){
                if(username.equals(cek.getString("username")) && password.equals(cek.getString("password")) && roles.equals(cek.getString("roles"))){
                    return true;
                }
            }
        }catch(SQLException ex){
            System.out.print(ex.toString());
        }
        return false;
    }
    
    public boolean cekRegist(String usernameRegist){
        String sqlcon = "select * from data";
                
        try{
            ResultSet cek = dbConnect.con.createStatement().executeQuery(sqlcon);
            while(cek.next()){
                if(usernameRegist.equals(cek.getString("username"))){
                    return true;
                }
            }
        }catch(SQLException ex){
            System.out.print(ex.toString());
        }
        return false;
    }
    
    public void cekRoles(String roles){
        if(roles.equals("Admin")){
            JOptionPane.showMessageDialog(null, "Login Sukses Sebagai Admin",
                        "Message", JOptionPane.INFORMATION_MESSAGE);
            dataPeminjamBuku();
        }else{
            JOptionPane.showMessageDialog(null, "Halo, " + userLogin.getText(),
                        "Message", JOptionPane.INFORMATION_MESSAGE);
            formPeminjamanBuku();
        }
    }
    
    public void dataPeminjamBuku(){
        DataPeminjamBuku baru = new DataPeminjamBuku();
        baru.setVisible(true);
    }
    
    public void formPeminjamanBuku(){
        FormPeminjamanBuku baru = new FormPeminjamanBuku();
        baru.setVisible(true);
    }
    /**
     * Creates new form Library_140201064
     */
    public Library_1402022066() {
        initComponents();
        Image img = new ImageIcon(this.getClass().getResource("/images/logoG.jpg")).getImage();
        this.setIconImage(img);
        dbConnect.koneksi();
        Register.setVisible(false);
    }
    int countClue = 1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Login = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userLogin = new javax.swing.JTextField();
        passLogin = new javax.swing.JPasswordField();
        rolesLogin = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        checkLogin = new javax.swing.JCheckBox();
        Register = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userRegist = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        passRegist = new javax.swing.JPasswordField();
        rolesRegist = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        checkRegist = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Copy Gramedia");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(101, 78, 146));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gramed-removebg-preview.png"))); // NOI18N

        Login.setBackground(new java.awt.Color(101, 78, 146));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(165, 192, 221));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOG IN NOW");

        jLabel3.setForeground(new java.awt.Color(165, 192, 221));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Belum punya akun? yuk buat dulu");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        userLogin.setBackground(new java.awt.Color(165, 192, 221));
        userLogin.setForeground(new java.awt.Color(0, 0, 0));
        userLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        passLogin.setBackground(new java.awt.Color(165, 192, 221));
        passLogin.setForeground(new java.awt.Color(0, 0, 0));
        passLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        rolesLogin.setBackground(new java.awt.Color(165, 192, 221));
        rolesLogin.setForeground(new java.awt.Color(0, 0, 0));
        rolesLogin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Masuk Sebagai", "Admin", "User" }));
        rolesLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton1.setBackground(new java.awt.Color(101, 78, 146));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(165, 192, 221));
        jButton1.setText("LOGIN");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(165, 192, 221));
        jLabel4.setText("Username");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(165, 192, 221));
        jLabel5.setText("Password");

        checkLogin.setBackground(new java.awt.Color(165, 192, 221));
        checkLogin.setForeground(new java.awt.Color(165, 192, 221));
        checkLogin.setText("show password");
        checkLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(userLogin)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                        .addComponent(passLogin)
                        .addComponent(rolesLogin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(70, 70, 70))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rolesLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        Register.setBackground(new java.awt.Color(101, 78, 146));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(165, 192, 221));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REGIST NOW!");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(165, 192, 221));
        jLabel7.setText("enter your username");

        userRegist.setBackground(new java.awt.Color(165, 192, 221));
        userRegist.setForeground(new java.awt.Color(0, 0, 0));
        userRegist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(165, 192, 221));
        jLabel8.setText("enter your password                      ");

        passRegist.setBackground(new java.awt.Color(165, 192, 221));
        passRegist.setForeground(new java.awt.Color(0, 0, 0));
        passRegist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passRegist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passRegistActionPerformed(evt);
            }
        });

        rolesRegist.setBackground(new java.awt.Color(165, 192, 221));
        rolesRegist.setForeground(new java.awt.Color(0, 0, 0));
        rolesRegist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daftar Sebagai", "Admin", "User" }));
        rolesRegist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton2.setBackground(new java.awt.Color(101, 78, 146));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(165, 192, 221));
        jButton2.setText("REGIST");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(165, 192, 221));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Udah punya akun? login yukk");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        checkRegist.setBackground(new java.awt.Color(165, 192, 221));
        checkRegist.setForeground(new java.awt.Color(165, 192, 221));
        checkRegist.setText("show password");
        checkRegist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRegistActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(165, 192, 221));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("?");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });

        javax.swing.GroupLayout RegisterLayout = new javax.swing.GroupLayout(Register);
        Register.setLayout(RegisterLayout);
        RegisterLayout.setHorizontalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkRegist, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(userRegist)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                        .addComponent(passRegist)
                        .addComponent(rolesRegist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(RegisterLayout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70))
        );
        RegisterLayout.setVerticalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userRegist, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passRegist, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkRegist)
                .addGap(7, 7, 7)
                .addComponent(rolesRegist, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        jLayeredPane1.setLayer(Login, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Register, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel1)
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(userRegist.getText().length() > 0){
            if(passRegist.getText().length() > 0){
                if(passRegist.getText().length() < 8){ 
                    JOptionPane.showMessageDialog(null, "Password minimal 8 karakter",
                        "Coba Lagi", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    if("Daftar Sebagai".equals("" + rolesRegist.getSelectedItem())){
                       JOptionPane.showMessageDialog(null, "Kamu belum pilih role",
                        "Coba Lagi", JOptionPane.INFORMATION_MESSAGE); 
                    }else{
                        if(cekRegist(userRegist.getText())){
                            JOptionPane.showMessageDialog(null, "Username ini telah digunakan",
                            "Warning", JOptionPane.ERROR_MESSAGE);
                        }else{
                            String sql = "insert into data(username, password, roles) values (?, ?, ?)";
                            try{
                                dbConnect.pst = dbConnect.con.prepareStatement(sql);
                                dbConnect.pst.setString(1, userRegist.getText());
                                dbConnect.pst.setString(2, passRegist.getText());
                                dbConnect.pst.setString(3, "" + rolesRegist.getSelectedItem());
                                dbConnect.pst.executeUpdate();
                                JOptionPane.showMessageDialog(this, "Akun Berhasil Dibuat");
                                //action reset semua yg udah diketik dan klik
                                userRegist.setText("");
                                passRegist.setText("");
                                rolesRegist.setSelectedIndex(0);
                                Register.setVisible(false);
                                Login.setVisible(true);
                                checkRegist.setSelected(false);
                            }catch(HeadlessException | SQLException ex){
                                JOptionPane.showMessageDialog(this, ex.getMessage());               
                            }
                        }
                    }
                } 
            }else{
                JOptionPane.showMessageDialog(null, "Kamu belum input pasword",
                     "Coba Lagi", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Kamu belum input username",
                "Coba Lagi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        userRegist.setText("");
        passRegist.setText("");
        rolesRegist.setSelectedIndex(0);
        checkRegist.setSelected(false);
        Login.setVisible(true);
        Register.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        userLogin.setText("");
        passLogin.setText("");
        rolesLogin.setSelectedIndex(0);
        checkLogin.setSelected(false);
        Login.setVisible(false);
        Register.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(userLogin.getText().length() > 0){
            if(passLogin.getText().length() > 0){
                if("Pilih Masuk Sebagai".equals("" + rolesLogin.getSelectedItem())){
                       JOptionPane.showMessageDialog(null, "Kamu belum pilih role",
                        "Coba Lagi", JOptionPane.INFORMATION_MESSAGE); 
                    }else{
                    if(cekLogin(userLogin.getText(), passLogin.getText(), "" + rolesLogin.getSelectedItem())){
                        cekRoles("" + rolesLogin.getSelectedItem());
                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "Pastikan username dan password yang anda masukkan benar",
                        "Login", JOptionPane.ERROR_MESSAGE); 
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "Kamu belum input pasword",
                     "Coba Lagi", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Kamu belum input username",
                "Coba Lagi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkRegistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRegistActionPerformed
        // TODO add your handling code here:
        if(checkRegist.isSelected()){
            passRegist.setEchoChar((char)0);
        }else{
            passRegist.setEchoChar('*');
        }
    }//GEN-LAST:event_checkRegistActionPerformed

    private void checkLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLoginActionPerformed
        // TODO add your handling code here:
        if(checkLogin.isSelected()){
            passLogin.setEchoChar((char)0);
        }else{
            passLogin.setEchoChar('*');
        }
    }//GEN-LAST:event_checkLoginActionPerformed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
        countClue++;
        if(countClue > 2)
            countClue = 1;
        if(countClue == 2){
            jLabel8.setText("enter your password                       min 8 karakter");
        }else if(countClue == 1){
            jLabel8.setText("enter your password                       ");
        }
    }//GEN-LAST:event_jLabel10MousePressed

    private void passRegistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passRegistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passRegistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Library_1402022066.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Library_1402022066.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Library_1402022066.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Library_1402022066.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Library_1402022066().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Register;
    private javax.swing.JCheckBox checkLogin;
    private javax.swing.JCheckBox checkRegist;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passLogin;
    private javax.swing.JPasswordField passRegist;
    private javax.swing.JComboBox<String> rolesLogin;
    private javax.swing.JComboBox<String> rolesRegist;
    private javax.swing.JTextField userLogin;
    private javax.swing.JTextField userRegist;
    // End of variables declaration//GEN-END:variables
}
